volumes:
  postgres_data:
    driver: local
  mlflow_data:
    driver: local
  mlflow_artifacts:
    driver: local
  data:


networks:
  mlops_network:
    driver: bridge

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:-keycloak}
    mem_limit: 300m
    container_name: postgres_loc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - mlops_network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    env_file:
      - ./.env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD:-keycloak}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    mem_limit: 500m
    command: start-dev
    container_name: keycloak_loc
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    restart: always
    networks:
      - mlops_network
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_loc
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:${KEYCLOAK_PORT}/
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - OLLAMA_HOST=http://host.docker.internal:11434
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - keycloak
      - postgres
      - mlflow
    networks:
      - mlops_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
      - APP_ENV=${APP_ENV}
      - KEYCLOAK_DOMAIN=${KEYCLOAK_DOMAIN}
      - KEYCLOAK_DOMAIN_LOCAL=${KEYCLOAK_DOMAIN_LOCAL}
    container_name: frontend_loc
    env_file:
      - ./.env
    depends_on:
      - keycloak
      - postgres
    ports:
      - "3000:80"
    networks:
      - mlops_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.4.0
    container_name: mlflow
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/artifacts
      - ./mlflow_data:/mlflow/db
    networks:
      - mlops_network
    restart: always
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/db/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    command: -p 5433
    networks:
      - mlops_network
    restart: unless-stopped
    volumes:
     - data:/home/postgres/pgdata/data

  vectorizer-worker:
   image: timescale/pgai-vectorizer-worker:latest
   environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@localhost:5433/postgres
      OLLAMA_HOST: http://host.docker.internal:11434
   networks:
      - mlops_network
   command: [ "--poll-interval", "5s" ]